config/routes.rb
BolaDePelo::Application.routes.draw do

  devise_for :users

  root :to => 'pages#home'
  get "pages/home", :as => :home

  resources :orders
  resources :clients do
    resources :dogs, only: :index, controller: "clients/dogs"
  end
  resources :dogs do
    get :orders, :on => :member
  end
  namespace :employee do
    resources :general_informations
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :dogs, foreign_key: 'owner_id'
  has_many :orders

  validates :name, :presence => true
end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner, :class_name => 'Client'
  has_many :orders

  validates :name, :presence => true
end

app/models/order.rb
class Order < ActiveRecord::Base
  module Status
    OPEN = 'aberto'
    CLOSED = 'fechado'
  end

  before_create do
    self.status = Status::OPEN
  end

  belongs_to :dog
  belongs_to :client

  accepts_nested_attributes_for :client, :dog

  default_scope :order => 'created_at desc'
  scope :open_today, where('created_at > ? AND status = ?', Time.now.at_beginning_of_day, Status::OPEN)
  scope :closed_today, where('created_at > ? AND status = ?', Time.now.at_beginning_of_day, Status::CLOSED)

  validates :client, :presence => true
  validates :dog, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         #:registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable
end

app/controllers/application_controller.rb
# encoding: utf-8
require 'app_responder'

class ApplicationController < ActionController::Base
  protect_from_forgery

  respond_to :json, :html

  before_filter :authenticate_user!
end

app/controllers/clients/dogs_controller.rb
class Clients::DogsController < ApplicationController
  def index
    @dogs = current_client.dogs
    respond_with(@dogs)
  end

  private
  def current_client
    id = params[:client_id]
    id ||= params[:id]
    @current_client ||= Client.find(id)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def orders
    @orders = Dog.find(params[:id]).orders.page(params[:page]).per(100)
    render '/orders/index', :layout => false
  end

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
    if params[:client_id]
      @dogs = Dog.where(:owner_id => params[:client_id])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dogs }
    end
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/new
  # GET /dogs/new.json
  def new
    @dog = Dog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dog }
    end
  end

  # GET /dogs/1/edit
  def edit
    @dog = Dog.find(params[:id])
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(params[:dog])

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render json: @dog, status: :created, location: @dog }
      else
        format.html { render action: "new" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dogs/1
  # PUT /dogs/1.json
  def update
    @dog = Dog.find(params[:id])

    respond_to do |format|
      if @dog.update_attributes(params[:dog])
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.page(params[:page]).per(15)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    params['order'].delete('client_attributes') unless params['order']['client_id'].blank?
    params['order'].delete('dog_attributes')    unless params['order']['dog_id'].blank?

    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        @order.dog.update_attribute :owner_id, @order.client.id
        format.html { redirect_to @order, notice: 'Pedido criado com sucesso!' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(order_params)
        format.html { redirect_to @order, notice: 'Pedido alterado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
  def order_params
    params.require(:order).permit(:client_id,
                                  :dog_id,
                                  :price,
                                  :info,
                                  :dog_attributes => [:name, :race],
                                  :client_attributes => [:name, :address, :phone])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client,
  :html => { :class => 'form-horizontal' }) do |f| %>

  <%= render 'shared/form_errors', :f => f %>

  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone %>

  <div class="form-actions">
    <%= f.submit :label => 'Salvar', :class => 'btn-primary' %>
    <%= link_to 'Cancelar', clients_path, :class => 'btn pull-right' %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Edtiar cliente</h1>

<%= render 'form' %>

app/views/clients/index.html.erb
<h1>Lista de Clientes Cadastrados</h1>

<table class="table dblclick-table">
  <tr>
    <th>Nome</th>
    <th>Endereço</th>
    <th>Telefone</th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr data-url="<%= url_for(client) %>">
    <td><%= client.name %></td>
    <td><%= client.address %></td>
    <td><%= client.phone %></td>
    <td><%= link_to 'Ver Cachorros', '#', class: "dogs-list", :'data-client-id' => client.id %></td>
  </tr>
<% end %>
</table>


<% content_for :javascripts do %>
  <script type="text/javascript">
    function render_dog(dog) {
      var str = dog.name;
      if (dog.race) str += " - " + dog.race;
      return str;
    }

    var compiled = _.template("<tr class='dogs'> \
      <td colspan='100'> \
        <div style='display:none'> \
          <ul> \
            <%% _.each(dogs, function(dog) { %> \
              <li> \
                <a href='dogs/<%%= dog.id %>' target='_blank'><%%= render_dog(dog) %></a> \
              </li> \
            <%% }); %> \
          </ul> \
        </div> \
      </td> \
    <tr>");

    $('a.dogs-list').click(function() {
      var tr = $('tr.dogs'),
        el = $(this);
      if (tr.length !== 0) {
        tr.find('div').slideUp(function () {
          tr.remove();
        });
        return;
      }
      var id = $(this).data('client-id'),
        self = this;

      $.get('dogs', {client_id: id}, function(data) {
        if (data.length === 0) {
          el.html('Sem cachorros');
          return;
        }
        $(self).parents('tr').after(compiled({dogs: data}));
        $('tr.dogs div').slideDown();
      }, 'json');
    });
  </script>
<% end %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @client.name %>
</p>

<p>
  <b>Endereço:</b>
  <%= @client.address %>
</p>

<p>
  <b>Telefone:</b>
  <%= @client.phone %>
</p>


<%= link_to 'Editar', edit_client_path(@client) %> |
<%= link_to 'Lista de Clientes', clients_path %>

app/views/dogs/_form.html.erb
<%= simple_form_for(@dog,
  :html => { :class => 'form-horizontal' }) do |f| %>

  <%= render 'shared/form_errors', :f => f %>

  <%= f.input :name %>
  <%= f.association :owner, :input_html => {
    :disabled => 'disabled' } %>
  <%= f.input :race %>

  <div class="form-actions">
    <%= f.submit :label => 'Salvar', :class => 'btn-primary' %>
    <%= link_to 'Cancelar', dogs_path, :class => 'btn pull-right' %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editar Cachorro</h1>

<%= render 'form' %>

app/views/dogs/index.html.erb
<h1>Cachorros Cadastrados</h1>

<table class="table dblclick-table">
  <tr>
    <th>Nome</th>
    <th>Dono</th>
    <th>Raça</th>
    <th>N.Atend.</th>
  </tr>

<% @dogs.each do |dog| %>
  <tr data-url="<%= url_for(dog) %>">
    <td><%= dog.name %></td>
    <td><%= dog.owner.name %></td>
    <td><%= dog.race %></td>
    <td><%= link_to_function dog.orders.count, "open_dog_orders(#{dog.id})" %></td>
  </tr>
<% end %>
</table>

<div class="modal hide" id="modal">
  <div class="modal-header" style="border-bottom: 0px">
    <button type="button" class="close" data-dismiss="modal">×</button>
  </div>
  <div class="modal-body">
  </div>
</div>


<% content_for :javascripts do %>
  <script type="text/javascript">
    $(document).ready(function() {
      window.open_dog_orders = function(dog_id) {
        $.get('/dogs/' + dog_id + '/orders/', function(data) {
          $('#modal .modal-body').html(data)
          $('#modal').modal();
        });
      }
    });
  </script>
<% end %>

app/views/dogs/new.html.erb
<h1>New dog</h1>

<%= render 'form' %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @dog.name %>
</p>

<p>
  <b>Dono:</b>
  <%= link_to @dog.owner.name, @dog.owner %>
</p>

<p>
  <b>Raça:</b>
  <%= @dog.race %>
</p>


<%= link_to 'Editar', edit_dog_path(@dog) %> |
<%= link_to 'Voltar', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BolaDePelo</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "/chosen/chosen.css" %>
  <%= stylesheet_link_tag "/twitter-bootstrap/css/bootstrap.css" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container" style="margin-top:20px">
    <div class="row">
    
      <div class="span8 offset2">
        <ul class="nav nav-tabs">
          <li class="<%= request.path == root_path ? 'active' : '' %>">
            <%= link_to 'Home', root_path %>
          </li>
          <%= content_tag :li, :class => controller.is_a?(OrdersController) ? 'active' : '' do %>
            <%= link_to 'Atendimento', orders_path %>
          <% end %>
          <%= content_tag :li, :class => controller.is_a?(DogsController) ? 'active' : '' do %>
            <%= link_to 'Cachorros', dogs_path %>
          <% end %>
          <%= content_tag :li, :class => controller.is_a?(ClientsController) ? 'active' : '' do %>
            <%= link_to 'Clientes', clients_path %>
          <% end %>
          <% if user_signed_in? %>
            <%= content_tag :li do %>
              <%= link_to 'Sair', destroy_user_session_path, :method => :delete %>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="row">

      <div class="span8 offset2">
        <%= yield %>
      </div>
    </div>
  </div>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "/chosen/chosen.jquery.js" %>
  <%= javascript_include_tag "/twitter-bootstrap/js/bootstrap.js" %>
  <%= yield :javascripts %>
</body>
</html>

app/views/orders/_form.html.erb
<% content_for :javascripts, javascript_include_tag('orders/form') %>

<style type="text/css">
select {
  width: 100%;
}
</style>

<%= simple_form_for(@order,
  :html => { :class => 'form-horizontal' }) do |f| %>
  
  <%= render 'shared/form_errors', :f => f %>

  <legend>Cliente</legend>
  <div id="client-select">
    <%= f.association :client,
      :collection => Client.all,
      :label_method => lambda {|client| client.name + ' - ' + client.phone },
      :input_html => {
        :'data-placeholder' => 'Escolha um cliente'
      },
      :include_blank => true %>
  </div>

  <div id="client-register">
    <% @order.build_client if @order.client.nil? %>
    <%= f.simple_fields_for :client do |fc| %>
      <%= fc.input :name %>
      <%= fc.input :address %>
      <%= fc.input :phone %>
    <% end %>
  </div>

  <legend>Cachorro</legend>
  <%= f.association :dog,
    input_html: { :'data-placeholder' => 'Escolha um Cachorro' },
    collection: [],
    include_blank: true  %>

  <% @order.build_dog if @order.dog.nil? %>
  <%= f.simple_fields_for :dog do |dog_form| %>
    <%= dog_form.input :name %>
    <%= dog_form.input :race %>
  <% end %>

  <legend>+ Informações</legend>
  <%= f.input :price %>
  <%= f.input :info, :as => :text,
    :input_html => {
      :rows => 10 } %>

  <div class="form-actions">
    <%= f.submit :label => 'Finalizar atendimento', :class => 'btn-primary' %>
    <%= link_to 'Cancelar', root_path, :class => 'btn pull-right' %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Lista de Atendimentos</h1>

<table class="table dblclick-table">
  <tr>
    <th>Cliente</th>
    <th>Cachorro</th>
    <th>Valor</th>
    <th>Feito a</th>
  </tr>

<% @orders.each do |order| %>
  <tr data-url=<%= url_for(order) %>>
    <td><%= order.client.name %></td>
    <td><%= order.dog.name %></td>
    <td>R$ <%= order.price %></td>
    <td><%= distance_of_time_in_words_to_now order.created_at %></td>
  </tr>
<% end %>
</table>

<br />
<%= paginate @orders %>

app/views/orders/new.html.erb
<h1>Novo Atendimento</h1>

<%= render 'form' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliente:</b>
  <%= @order.client.name %>
</p>

<p>
  <b>Cachorro:</b>
  <%= @order.dog.name %>
</p>

<p>
  <b>Valor:</b>
  <%= @order.price %>
</p>

<p>
  <b>Situação:</b>
  <%= t(".status.#{@order.status}") %>
</p>


<%= link_to 'Editar', edit_order_path(@order) %>

app/views/pages/home.html.erb
<style type="text/css">
  .add-margin { margin-top: 10pt; }
</style>

<h2>Pedidos do dia</h2>

<% if (@today_orders = Order.open_today).empty? %>
  <h3>Nenhum Pedido em aberto hoje</h3>
<% end %>

<table class="table dblclick-table">
  <% @today_orders.each do |order| %>
    <tr data-url="<%= url_for(order) %>">
      <td><%= order.client.name %></td>
      <td><%= order.dog.name %></td>
      <td>R$ <%= order.price %></td>
      <td><%= distance_of_time_in_words_to_now order.created_at %></td>
      <td>
        <%= form_tag order,
          :method => :put,
          :remote => true,
          :class => 'close-order',:style => 'display:inline' do %>
          <%= hidden_field_tag 'order[status]', Order::Status::CLOSED %>
          <%= link_to 'fechar', '', :onclick => '$(this).parent("form").submit()', :confirm => 'Deseja mesmo fechar este pedido?' %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

<hr>



<h2 class="add-margin">Últimos pedidos atendidos</h2>

<% if (@closed_today = Order.closed_today).empty? %>
  <h3>Nenhum Pedido feito hoje</h3>
<% end %>

<table class="table dblclick-table">
  <% @closed_today.each do |order| %>
    <tr data-url="<%= url_for(order) %>">
      <td><%= order.client.name %></td>
      <td><%= order.dog.name %></td>
      <td>R$ <%= order.price %></td>
      <td><%= distance_of_time_in_words_to_now order.created_at %></td>
    </tr>
  <% end %>
</table>

<hr>



<%= link_to content_tag(:h2, 'Novo pedido', :class => 'add-margin'), new_order_path %>


<% content_for :javascripts do %>
  <script type="text/javascript">
    $('form.close-order')
      .bind('ajax:success', function(){ window.location.reload(true) })
      .bind('ajax:failure', function(){ alert('Erro ao fechar pedido, tente novamente mais tarde') });
  </script>
<% end %>

app/views/shared/_form_errors.html.erb
<% if notification = f.error_notification %>
  <%= notification %>
<% end %>